In [1]:
import torch
import math

In [2]:
# Tensor만들기

x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[5.8610e-28, 3.0690e-41, 3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


In [4]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [5]:
# 랜덤 텐서 시드
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [6]:
# 텐서 모양
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[1.5872e-27, 3.0690e-41, 4.4842e-44],
         [0.0000e+00,        nan, 0.0000e+00]],

        [[1.0948e+21, 9.2868e-04, 1.3556e-19],
         [9.8864e-33, 1.0008e+01, 2.5591e-41]]])
torch.Size([2, 2, 3])
tensor([[[1.5760e-27, 3.0690e-41, 3.3631e-44],
         [0.0000e+00,        nan, 0.0000e+00]],

        [[1.1578e+27, 1.1362e+30, 7.1547e+22],
         [4.5828e+30, 1.2121e+04, 7.1846e+22]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [7]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])


# tensor 데이터 타입
- torch.bool
- torch.int8
- torch.uint8
- torch.int16
- torch.int32
- torch.int64
- torch.half
- torch.float
- torch.double
- torch.bfloat

In [9]:
# tensor 데이터 타입
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float64) * 20
print(b)

# tensor data type 변경
c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.3283,  0.2118, 18.4972],
        [ 9.8370,  3.8937, 16.1945]], dtype=torch.float64)
tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


In [10]:
# 수학적 논리

ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [11]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [13]:
# 행렬의 크기가 맞지 않음
# a = torch.rand(2, 3)
# b = torch.rand(3, 2)
# print(a * b)

rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.7220, 0.8217, 0.2612, 0.7375],
        [0.8328, 0.8444, 0.2941, 0.3788]])
tensor([[1.4439, 1.6434, 0.5224, 1.4750],
        [1.6657, 1.6888, 0.5882, 0.7576]])


In [17]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2)
print(b)

c = a * torch.rand(3, 1)
print(c)

d = a * torch.rand(1, 2)
print(d)


tensor([[[0.8073, 0.2125],
         [0.3977, 0.3132],
         [0.6331, 0.8222]],

        [[0.8073, 0.2125],
         [0.3977, 0.3132],
         [0.6331, 0.8222]],

        [[0.8073, 0.2125],
         [0.3977, 0.3132],
         [0.6331, 0.8222]],

        [[0.8073, 0.2125],
         [0.3977, 0.3132],
         [0.6331, 0.8222]]])
tensor([[[0.2652, 0.2652],
         [0.7328, 0.7328],
         [0.2126, 0.2126]],

        [[0.2652, 0.2652],
         [0.7328, 0.7328],
         [0.2126, 0.2126]],

        [[0.2652, 0.2652],
         [0.7328, 0.7328],
         [0.2126, 0.2126]],

        [[0.2652, 0.2652],
         [0.7328, 0.7328],
         [0.2126, 0.2126]]])
tensor([[[0.4408, 0.3877],
         [0.4408, 0.3877],
         [0.4408, 0.3877]],

        [[0.4408, 0.3877],
         [0.4408, 0.3877],
         [0.4408, 0.3877]],

        [[0.4408, 0.3877],
         [0.4408, 0.3877],
         [0.4408, 0.3877]],

        [[0.4408, 0.3877],
         [0.4408, 0.3877],
         [0.4408, 0.3877]]])
tens

# 더 수학적 텐서
https://pytorch.org/docs/stable/torch.html#math-operations

In [18]:
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a)) # 절대값
print(torch.ceil(a)) # 각 요소보다 크거나 같은 최소 정수인 입력 요소의 ceil이 포함된 새 텐서를 반환합니다.
print(torch.floor(a)) # 입력 요소의 바닥이 있는 새 텐서를 반환합니다. 각 요소보다 작거나 같은 최대 정수입니다.
print(torch.clamp(a, -0.5, 0.5)) # 입력된 모든 요소를 [min, max] 범위로 클램프합니다.


Common functions:
tensor([[0.4235, 0.4804, 0.1066, 0.6997],
        [0.7201, 0.8560, 0.6028, 0.6442]])
tensor([[1., 1., -0., 1.],
        [-0., 1., -0., -0.]])
tensor([[ 0.,  0., -1.,  0.],
        [-1.,  0., -1., -1.]])
tensor([[ 0.4235,  0.4804, -0.1066,  0.5000],
        [-0.5000,  0.5000, -0.5000, -0.5000]])


In [21]:
# 삼각함수와 역함수
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles) # 각 입력 요소가 라디안 단위의 각도에서 각도로 변환된 새 텐서를 반환합니다.
print(sines) # 입력 요소의 사인 값을 사용하여 새 텐서를 반환합니다.
print(inverses) # 입력 요소의 asin이 포함된 새 텐서를 반환합니다.


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [22]:
# bitwise operations 입력 및 기타 비트 단위 XOR를 계산합니다.
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


Bitwise XOR:
tensor([3, 2, 1])


In [28]:
# comparisons
print('\nBroadcasted, element-wise equality comparison: ')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2) 
print(torch.eq(d, e)) # 행렬 비교 연산 후 boolean 타입 반환


Broadcasted, element-wise equality comparison: 
tensor([[ True, False],
        [False, False]])


In [30]:
# reductions:
print('\nReduction ops:')
print(torch.max(d)) # 가장 큰 싱글 텐서 리턴
print(torch.max(d).item()) # 큰 싱글 텐서 값  추출
print(torch.mean(d)) # 평균
print(torch.std(d)) # 표준편차
print(torch.prod(d)) # 모든 숫자 곱
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # 유니코한 요소 리턴


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [32]:
# 벡터와 선형 연산
v1 = torch.tensor([1., 0., 0.]) # x 축 벡터
v2 = torch.tensor([0., 1., 0.])
m1 = torch.rand(2, 2)
m2 = torch.tensor([[3., 0.], [0., 3.]]) # 3차원 매트릭스

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # 벡터의 교차곱을 반환
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)
print(torch.svd(m3)) # 특이값 분해


Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.2659, 0.5251],
        [0.1631, 0.7391]])
tensor([[0.7978, 1.5754],
        [0.4894, 2.2173]])
torch.return_types.svd(
U=tensor([[ 0.6109,  0.7917],
        [ 0.7917, -0.6109]]),
S=tensor([2.8552, 0.3495]),
V=tensor([[ 0.3064,  0.9519],
        [ 0.9519, -0.3064]]))


In [33]:
# 텐서 교체
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb: ')
print(b)
print(torch.sin_(b))
print(b)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b: 
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [34]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before: ')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before: 
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9254, 0.2546],
        [0.9369, 0.7488]])

After adding:
tensor([[1.9254, 1.2546],
        [1.9369, 1.7488]])
tensor([[1.9254, 1.2546],
        [1.9369, 1.7488]])
tensor([[0.9254, 0.2546],
        [0.9369, 0.7488]])

After multiplying
tensor([[0.8564, 0.0648],
        [0.8778, 0.5606]])
tensor([[0.8564, 0.0648],
        [0.8778, 0.5606]])


In [39]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)

assert c is d # c와 d가 동일한 객체 인지 확인
assert id(c), old_id # 새로운 c가 이전 객체와 동일한지 확인

torch.rand(2, 2, out=c)
print(c) # c가 다시 바뀜
assert id(c), old_id # 여전히 똑같은 객체

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3925, 0.4236],
        [0.8706, 1.0576]])
tensor([[0.1619, 0.0425],
        [0.0313, 0.5074]])


# 텐서 복제

In [40]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [43]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # 다른 메모리에 복제함
print(torch.eq(a, b)) # 같은 객체

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


소스텐서가 autograd를 활성화하면 클론도 활성화 된다

In [45]:
a = torch.rand(2, 2, requires_grad=True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.8454, 0.1194],
        [0.7245, 0.6522]], requires_grad=True)
tensor([[0.8454, 0.1194],
        [0.7245, 0.6522]], grad_fn=<CloneBackward0>)
tensor([[0.8454, 0.1194],
        [0.7245, 0.6522]])
tensor([[0.8454, 0.1194],
        [0.7245, 0.6522]], requires_grad=True)


# GPU 사용

In [46]:
if torch.cuda.is_available():
  print("We have a GPU!")
else:
  print('Sorry, CPU only.')

Sorry, CPU only.


In [47]:
if torch.cuda.is_available():
  gpu_rand = torch.rand(2, 2, device = 'cuda')
  print(gpu_rand)
else:
  print('Sorry, CPU only.')

Sorry, CPU only.


In [48]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.1779, 0.7497],
        [0.9760, 0.5971]])


In [49]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [1]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='gpu')
z = x + y  # exception will be thrown

NameError: ignored