# 텐서
- 텐서는 배열(array)나 행렬(matrix)와 같은 특수한 자료
- Pytorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 모델의 매개변수들을 부호화(encode) 함
- tensor는 numpy와 유사하며 GPU나 다른 하드웨어 가속기에서 실행 가능
- 자동 미분에 최적화 되어 있음

In [1]:
import torch
import numpy as np

# 텐서 초기화 방법

In [7]:
# 데이터로부터 직접 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# numpy로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# 다른 텐서로 부터 생성
x_ones = torch.ones_like(x_data) # x_data 속성 유지(속성 그대로 1의 텐서 행렬)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성을 덮어씀(속성 그대로 랜덤 텐서 행렬)
print("Random Tensor : \n {} \n".format(x_rand))


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.2563, 0.7697],
        [0.0878, 0.4764]]) 

Random Tensor: 
 tensor([[0.2584, 0.9637, 0.8844],
        [0.0440, 0.0357, 0.2734]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [8]:
# 무작위(random) 또는 상수(constant)값을 사용하기
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("Random Tensor: \n {} \n".format(rand_tensor))
print("Ones Tensor: \n {} \n".format(ones_tensor))
print("Zeros Tensor: \n {} \n".format(zeros_tensor))

Random Tensor: 
 tensor([[0.3679, 0.6728, 0.9860],
        [0.2433, 0.9205, 0.5366]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [9]:
# 텐서의 속성

tensor = torch.rand(3, 4)

print("Shape of tensor: {}".format(tensor.shape))
print("Datatype of tensor: {}".format(tensor.dtype))
print("Device tensor is stored on: {}".format(tensor.device))

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 텐서 연산

- 전치, 인덱싱, 슬라이싱 ,수학계산, 선형 대수, 임의 샘플링 연산 확인
https://pytorch.org/docs/stable/torch.html


In [10]:
# GPU가 존재하면 텐서를 이동

if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [12]:
# Numpy식의 표준 인덱싱과 슬라이싱

tensor = torch.ones(4, 4)
print("First row: ", tensor[0])
print("First column: ", tensor[:, 0])
print("Last column: ", tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [14]:
# 산술 연산
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산 y1, y2, y3은 모두 같은 값을 갖는다

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out = y3)

# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖음
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [19]:
# 단일 요소 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우, item()을 사용하여 python 숫자 값으로 변환
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [20]:
# in-place 연산

print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# 텐서를 numpy변환 
- cpu 상의 텐서와 numpy 배열은 메모리 공간을 공유 -> 하나를 변경하면 다른 하나도 변경

In [22]:
t = torch.ones(5)
print("t: {}".format(t))

n = t.numpy()
print("n: {}".format(n))

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [23]:
t.add_(1)
print("t: {}".format(t))
print("n: {}".format(n))

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [24]:
n = np.ones(5)
t = torch.from_numpy(n)

In [25]:
np.add(n, 1, out=n)
print("t: {}".format(t))
print("n: {}".format(n))


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
