In [2]:
import torch
import math

In [2]:
# Tensor만들기

x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.4495e+38, 3.0936e-41, 3.3631e-44, 0.0000e+00],
        [       nan, 3.0936e-41, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [4]:
# 랜덤 텐서 시드
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [5]:
# 텐서 모양
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[1.4496e+38, 3.0936e-41, 2.1624e-01],
         [9.9269e-01, 4.1275e-01, 5.9382e-01]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[1.4496e+38, 3.0936e-41, 3.3631e-44],
         [0.0000e+00,        nan, 5.9382e-01]],

        [[1.1578e+27, 1.1362e+30, 7.1547e+22],
         [4.5828e+30, 1.2121e+04, 7.1846e+22]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [6]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])


# tensor 데이터 타입
- torch.bool
- torch.int8
- torch.uint8
- torch.int16
- torch.int32
- torch.int64
- torch.half
- torch.float
- torch.double
- torch.bfloat

In [7]:
# tensor 데이터 타입
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float64) * 20
print(b)

# tensor data type 변경
c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [8]:
# 수학적 논리

ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [9]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [10]:
# 행렬의 크기가 맞지 않음
# a = torch.rand(2, 3)
# b = torch.rand(3, 2)
# print(a * b)

rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614]])
tensor([[1.2291, 1.1998, 1.0026, 1.8793],
        [1.7312, 1.0413, 1.3730, 0.7228]])


In [11]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2)
print(b)

c = a * torch.rand(3, 1)
print(c)

d = a * torch.rand(1, 2)
print(d)


tensor([[[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]]])
tensor([[[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]]])
tensor([[[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]]])


# 더 수학적 텐서
https://pytorch.org/docs/stable/torch.html#math-operations

In [12]:
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a)) # 절대값
print(torch.ceil(a)) # 각 요소보다 크거나 같은 최소 정수인 입력 요소의 ceil이 포함된 새 텐서를 반환합니다.
print(torch.floor(a)) # 입력 요소의 바닥이 있는 새 텐서를 반환합니다. 각 요소보다 작거나 같은 최대 정수입니다.
print(torch.clamp(a, -0.5, 0.5)) # 입력된 모든 요소를 [min, max] 범위로 클램프합니다.


Common functions:
tensor([[0.9238, 0.5724, 0.0791, 0.2629],
        [0.1986, 0.4439, 0.6434, 0.4776]])
tensor([[-0., -0., 1., -0.],
        [-0., 1., 1., -0.]])
tensor([[-1., -1.,  0., -1.],
        [-1.,  0.,  0., -1.]])
tensor([[-0.5000, -0.5000,  0.0791, -0.2629],
        [-0.1986,  0.4439,  0.5000, -0.4776]])


In [13]:
# 삼각함수와 역함수
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles) # 각 입력 요소가 라디안 단위의 각도에서 각도로 변환된 새 텐서를 반환합니다.
print(sines) # 입력 요소의 사인 값을 사용하여 새 텐서를 반환합니다.
print(inverses) # 입력 요소의 asin이 포함된 새 텐서를 반환합니다.


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [14]:
# bitwise operations 입력 및 기타 비트 단위 XOR를 계산합니다.
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


Bitwise XOR:
tensor([3, 2, 1])


In [15]:
# comparisons
print('\nBroadcasted, element-wise equality comparison: ')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2) 
print(torch.eq(d, e)) # 행렬 비교 연산 후 boolean 타입 반환


Broadcasted, element-wise equality comparison: 
tensor([[ True, False],
        [False, False]])


In [16]:
# reductions:
print('\nReduction ops:')
print(torch.max(d)) # 가장 큰 싱글 텐서 리턴
print(torch.max(d).item()) # 큰 싱글 텐서 값  추출
print(torch.mean(d)) # 평균
print(torch.std(d)) # 표준편차
print(torch.prod(d)) # 모든 숫자 곱
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # 유니코한 요소 리턴


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [17]:
# 벡터와 선형 연산
v1 = torch.tensor([1., 0., 0.]) # x 축 벡터
v2 = torch.tensor([0., 1., 0.])
m1 = torch.rand(2, 2)
m2 = torch.tensor([[3., 0.], [0., 3.]]) # 3차원 매트릭스

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # 벡터의 교차곱을 반환
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)
print(torch.svd(m3)) # 특이값 분해


Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.7375, 0.8328],
        [0.8444, 0.2941]])
tensor([[2.2125, 2.4985],
        [2.5332, 0.8822]])
torch.return_types.svd(
U=tensor([[-0.7889, -0.6145],
        [-0.6145,  0.7889]]),
S=tensor([4.1498, 1.0548]),
V=tensor([[-0.7957,  0.6056],
        [-0.6056, -0.7957]]))


In [18]:
# 텐서 교체
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb: ')
print(b)
print(torch.sin_(b))
print(b)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b: 
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [19]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before: ')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before: 
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3788, 0.4567],
        [0.0649, 0.6677]])

After adding:
tensor([[1.3788, 1.4567],
        [1.0649, 1.6677]])
tensor([[1.3788, 1.4567],
        [1.0649, 1.6677]])
tensor([[0.3788, 0.4567],
        [0.0649, 0.6677]])

After multiplying
tensor([[0.1435, 0.2086],
        [0.0042, 0.4459]])
tensor([[0.1435, 0.2086],
        [0.0042, 0.4459]])


In [20]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)

assert c is d # c와 d가 동일한 객체 인지 확인
assert id(c), old_id # 새로운 c가 이전 객체와 동일한지 확인

torch.rand(2, 2, out=c)
print(c) # c가 다시 바뀜
assert id(c), old_id # 여전히 똑같은 객체

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3653, 0.8699],
        [0.2364, 0.3604]])
tensor([[0.0776, 0.4004],
        [0.9877, 0.0352]])


# 텐서 복제

In [21]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [22]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # 다른 메모리에 복제함
print(torch.eq(a, b)) # 같은 객체

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


소스텐서가 autograd를 활성화하면 클론도 활성화 된다

In [23]:
a = torch.rand(2, 2, requires_grad=True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]], requires_grad=True)
tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]], grad_fn=<CloneBackward0>)
tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]])
tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]], requires_grad=True)


# GPU 사용

In [24]:
if torch.cuda.is_available():
  print("We have a GPU!")
else:
  print('Sorry, CPU only.')

We have a GPU!


In [25]:
if torch.cuda.is_available():
  gpu_rand = torch.rand(2, 2, device = 'cuda')
  print(gpu_rand)
else:
  print('Sorry, CPU only.')

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


In [26]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cuda
tensor([[0.0024, 0.6778],
        [0.2441, 0.6812]], device='cuda:0')


In [27]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [31]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='cpu')
z = x + y  # exception will be thrown

# 텐서 형태 조작

In [32]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [33]:
c = torch.rand(1,1,1,1,1)
print(c)

tensor([[[[[0.3277]]]]])


In [3]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.5632, 0.4335, 0.2502, 0.5036, 0.1747, 0.8876, 0.5998, 0.8965, 0.9101,
         0.4517, 0.6464, 0.8106, 0.2295, 0.9399, 0.8340, 0.0507, 0.0898, 0.0656,
         0.4013, 0.9560]])
torch.Size([20])
tensor([0.5632, 0.4335, 0.2502, 0.5036, 0.1747, 0.8876, 0.5998, 0.8965, 0.9101,
        0.4517, 0.6464, 0.8106, 0.2295, 0.9399, 0.8340, 0.0507, 0.0898, 0.0656,
        0.4013, 0.9560])
torch.Size([2, 2])
torch.Size([2, 2])


In [7]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3,1)
print(c)

tensor([[[0.3573, 0.3573],
         [0.6556, 0.6556],
         [0.9515, 0.9515]],

        [[0.3573, 0.3573],
         [0.6556, 0.6556],
         [0.9515, 0.9515]],

        [[0.3573, 0.3573],
         [0.6556, 0.6556],
         [0.9515, 0.9515]],

        [[0.3573, 0.3573],
         [0.6556, 0.6556],
         [0.9515, 0.9515]]])
tensor([[0.7039],
        [0.9133],
        [0.9417]])


In [8]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)
c = b.unsqueeze(1)
print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.7307, 0.7307],
         [0.4635, 0.4635],
         [0.3305, 0.3305]],

        [[0.7307, 0.7307],
         [0.4635, 0.4635],
         [0.3305, 0.3305]],

        [[0.7307, 0.7307],
         [0.4635, 0.4635],
         [0.3305, 0.3305]],

        [[0.7307, 0.7307],
         [0.4635, 0.4635],
         [0.3305, 0.3305]]])


In [9]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [10]:
output3d = torch.rand(6, 20 ,20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


# Numpy Bridge
- numpy array와 pytorch 변환이 쉽다

In [11]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.7404, 0.1894, 0.7904],
        [0.0145, 0.4138, 0.0485]])
[[0.74041426 0.18943411 0.7904206 ]
 [0.01448184 0.41381562 0.04854256]]


In [14]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[7.40414262e-01 1.89434111e-01 7.90420592e-01]
 [1.44818425e-02 1.70000000e+01 4.85425591e-02]]
