In [1]:
import torch

In [2]:
torch.__version__

'1.10.0+cu111'

# 초기화되지 않은 행렬


In [3]:
x = torch.empty(4,2 )
print(x)

tensor([[3.3136e+06, 3.0718e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30]])


# 초기화 된 행렬

In [4]:
x = torch.rand(4, 2)
print(x)

tensor([[0.3382, 0.8874],
        [0.9499, 0.6426],
        [0.2179, 0.5881],
        [0.7353, 0.0262]])


# dtype이 long, 0으로 채워진 텐서

In [5]:
x = torch.zeros(4, 2, dtype = torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [7]:
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])


In [9]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x, dtype = torch.float) # 모양은 그대로 가지고 오면서 값은 랜덤 지정
print(x)

tensor([[ 0.3380,  0.0419,  1.1530,  2.1837],
        [-0.5019, -1.6438, -0.1148, -0.8933]])


# 텐서의 크기

In [11]:
print(x.size())

torch.Size([2, 4])


In [12]:
print(x)

tensor([[ 0.3380,  0.0419,  1.1530,  2.1837],
        [-0.5019, -1.6438, -0.1148, -0.8933]])


In [14]:
y = torch.rand(2,4)
print(y)
print(x + y)

tensor([[0.2141, 0.3271, 0.8669, 0.8397],
        [0.9252, 0.3552, 0.1911, 0.2484]])
tensor([[ 0.5522,  0.3690,  2.0199,  3.0234],
        [ 0.4233, -1.2886,  0.0763, -0.6449]])


In [15]:
print(torch.add(x, y))

tensor([[ 0.5522,  0.3690,  2.0199,  3.0234],
        [ 0.4233, -1.2886,  0.0763, -0.6449]])


In [16]:
result = torch.empty(2, 4)
torch.add(x, y, out = result) # 더한 연산을 result에 뺌
print(result)

tensor([[ 0.5522,  0.3690,  2.0199,  3.0234],
        [ 0.4233, -1.2886,  0.0763, -0.6449]])


# 덧셈4
   - in-place 방식
   - (참고) in-place 방식
      - in-place 방식으로 텐서의 값을 변경하는 연산 뒤에는 "_"가 붙음
      - x.copy_(y), x.t_()

In [17]:
print(x)
print(y)
y.add_(x) # y += x
print(y)

tensor([[ 0.3380,  0.0419,  1.1530,  2.1837],
        [-0.5019, -1.6438, -0.1148, -0.8933]])
tensor([[0.2141, 0.3271, 0.8669, 0.8397],
        [0.9252, 0.3552, 0.1911, 0.2484]])
tensor([[ 0.5522,  0.3690,  2.0199,  3.0234],
        [ 0.4233, -1.2886,  0.0763, -0.6449]])


# 그 외의 연산
  - torch.sub : 뺄셈
  - torch.mul : 곱셈
  - torch.div : 나누셈
  - torch.mm : 내적(dot product)

In [18]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [23]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])


In [24]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x/y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])


In [25]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])

print(torch.mm(x,y))

tensor([[20., 28.],
        [52., 76.]])


# 인덱싱
  - 넘파이처럼 인덱싱 사용가능

In [27]:
print(x[:, 1])

tensor([3., 7.])


In [29]:
x = torch.randn(4, 5) # 텐서의 크기(size)나 모양(shape)을 변경
y = x.view(20)
z = x.view(5, -1)

print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 5])
torch.Size([20])
torch.Size([5, 4])


In [30]:
x = torch.randn(1) 
print(x)
print(x.item()) # 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음
print(x.dtype)

tensor([-1.2390])
-1.2390319108963013
torch.float32


# 차원을 축소(제거)

In [33]:
tensor = torch.rand(1, 3, 3)
tensor.shape

print(tensor)

tensor([[[0.3212, 0.2706, 0.3336],
         [0.2805, 0.7779, 0.7616],
         [0.5590, 0.0782, 0.9334]]])


In [32]:
t = tensor.squeeze()

print(t)
print(t.shape)

tensor([[0.4601, 0.9477, 0.6856],
        [0.0920, 0.5240, 0.5906],
        [0.8111, 0.3304, 0.7542]])
torch.Size([3, 3])


In [34]:
t = tensor.unsqueeze(dim = 0) # 차원을 증가 

print(t)
print(t.shape)

tensor([[[[0.3212, 0.2706, 0.3336],
          [0.2805, 0.7779, 0.7616],
          [0.5590, 0.0782, 0.9334]]]])
torch.Size([1, 1, 3, 3])
